import * as YUKA from "yuka";
import { findPath } from "./algorithm.js";
import {
  waypointsA,
  waypointsB,
  roadSegmentsA,
  roadSegmentsB,
  meshIslandsA,
  meshIslandsB,
} from "./waypoints.js";
import { safetyThreshold, activeTownLetter } from "./Experience.jsx";
import { act } from "@react-three/fiber";

export let path = new YUKA.Path();

// A class to build our road segments that I will use to calculate safety scores
class RoadSegment {
  constructor({
    roadCondition,
    trafficDensity,
    visibility,
    accidentHistory,
    pedestrianDensity,
    speedLimit,
    proximityToSensitiveAreas,
    emergencyResponseAccessibility,
    vehicleMix,
    roadWidth,
    trafficSignalDensity,
    pedestrianInfrastructure,
    schoolZoneProximity,
    constructionZones,
    timeOfDay,
    publicEventProximity,
    weatherConditions,
    signalTiming,
    publicTransportProximity,
    wildlifeCrossing,
    localDrivingCulture,
    alternativeRoutesAvailability,
    networkConnectivity,
  }) {
    this.roadCondition = roadCondition;
    this.trafficDensity = trafficDensity;
    this.visibility = visibility;
    this.accidentHistory = accidentHistory;
    this.pedestrianDensity = pedestrianDensity;
    this.speedLimit = speedLimit;
    this.proximityToSensitiveAreas = proximityToSensitiveAreas;
    this.emergencyResponseAccessibility = emergencyResponseAccessibility;
    this.vehicleMix = vehicleMix;
    this.roadWidth = roadWidth;
    this.trafficSignalDensity = trafficSignalDensity;
    this.pedestrianInfrastructure = pedestrianInfrastructure;
    this.schoolZoneProximity = schoolZoneProximity;
    this.constructionZones = constructionZones;
    this.timeOfDay = timeOfDay;
    this.publicEventProximity = publicEventProximity;
    this.weatherConditions = weatherConditions;
    this.signalTiming = signalTiming;
    this.publicTransportProximity = publicTransportProximity;
    this.wildlifeCrossing = wildlifeCrossing;
    this.localDrivingCulture = localDrivingCulture;
    this.alternativeRoutesAvailability = alternativeRoutesAvailability;
    this.networkConnectivity = networkConnectivity;
  }
}

// Here's the waypoints for townA, that I will then update to include safety scores and distances
export let waypoints = {
  A: {
    coordinates: new YUKA.Vector3(-0.0908522829413414, 0, 3.062549591064453),
    neighbours: ["D"],
  },
  B: {
    coordinates: new YUKA.Vector3(-4.258955001831055, 0, 2.4583702087402344),
    neighbours: ["M", "C"],
  },
  C: {
    coordinates: new YUKA.Vector3(-3.6725292205810547, 0, 2.4583702087402344),
    neighbours: ["B", "D", "L"],
  },
  D: {
    coordinates: new YUKA.Vector3(-0.18015336990356445, 0, 2.4583702087402344),
    neighbours: ["A", "C", "J", "K", "E"],
  },
  E: {
    coordinates: new YUKA.Vector3(2.6552371978759766, 0, 2.4583702087402344),
    neighbours: ["F", "D", "H"],
  },
  F: {
    coordinates: new YUKA.Vector3(3.478020191192627, 0, 2.4583702087402344),
    neighbours: ["E", "G"],
  },
  G: {
    coordinates: new YUKA.Vector3(3.478020191192627, 0, 1.19381844997406),
    neighbours: ["F", "H", "T"],
  },
  H: {
    coordinates: new YUKA.Vector3(2.0038840770721436, 0, 1.19381844997406),
    neighbours: ["E", "G", "R", "S"],
  },
  I: {
    coordinates: new YUKA.Vector3(0.6296098232269287, 0, 1.19381844997406),
    neighbours: ["D", "H", "J", "R"],
  },
  J: {
    coordinates: new YUKA.Vector3(-0.11812174320220947, 0, 1.19381844997406),
    neighbours: ["D", "I", "K", "Q"],
  },
  K: {
    coordinates: new YUKA.Vector3(-0.7302283644676208, 0, 1.19381844997406),
    neighbours: ["D", "J", "L", "P"],
  },
  L: {
    coordinates: new YUKA.Vector3(-3.1584267616271973, 0, 1.19381844997406),
    neighbours: ["C", "M", "O", "K"],
  },
  M: {
    coordinates: new YUKA.Vector3(-4.201684951782227, 0, 1.19381844997406),
    neighbours: ["N", "L"],
  },
  N: {
    coordinates: new YUKA.Vector3(-4.201684951782227, 0, -0.10426831245422363),
    neighbours: ["O", "V", "M"],
  },
  O: {
    coordinates: new YUKA.Vector3(-2.720555305480957, 0, -0.10426831245422363),
    neighbours: ["N", "V", "L", "Y", "P"],
  },
  P: {
    coordinates: new YUKA.Vector3(-1.3455042839050293, 0, -0.10426831245422363),
    neighbours: ["Y", "O", "K", "Q"],
  },
  Q: {
    coordinates: new YUKA.Vector3(-0.114859938621521, 0, -0.10426831245422363),
    neighbours: ["P", "J", "R", "Z"],
  },
  R: {
    coordinates: new YUKA.Vector3(1.240871787071228, 0, -0.10426831245422363),
    neighbours: ["Q", "I", "H", "S", "AA"],
  },
  S: {
    coordinates: new YUKA.Vector3(2.5966243743896484, 0, -0.10426831245422363),
    neighbours: ["U", "R", "H", "T"],
  },
  T: {
    coordinates: new YUKA.Vector3(3.485111951828003, 0, -0.10426831245422363),
    neighbours: ["U", "S", "G"],
  },
  U: {
    coordinates: new YUKA.Vector3(2.8128910064697266, 0, -0.7648482322692871),
    neighbours: ["AB", "AC", "S", "T"],
  },
  V: {
    coordinates: new YUKA.Vector3(-3.625488042831421, 0, -0.9578653573989868),
    neighbours: ["O", "N", "W", "X", "Y"],
  },
  W: {
    coordinates: new YUKA.Vector3(-4.4565749168396, 0, -1.7634589672088623),
    neighbours: ["V", "X"],
  },
  X: {
    coordinates: new YUKA.Vector3(-3.069730281829834, 0, -1.7634589672088623),
    neighbours: ["W", "V", "Y", "AF"],
  },
  Y: {
    coordinates: new YUKA.Vector3(-2.1570639610290527, 0, -1.7634589672088623),
    neighbours: ["AF", "X", "O", "P", "Z"],
  },
  Z: {
    coordinates: new YUKA.Vector3(-0.1685734987258911, 0, -1.7634589672088623),
    neighbours: ["Y", "Q", "AA", "AE"],
  },
  AA: {
    coordinates: new YUKA.Vector3(0.4177762269973755, 0, -1.7634589672088623),
    neighbours: ["Z", "AE", "AB", "R"],
  },
  AB: {
    coordinates: new YUKA.Vector3(1.9218908548355103, 0, -1.7634589672088623),
    neighbours: ["AA", "U", "AC", "AD"],
  },
  AC: {
    coordinates: new YUKA.Vector3(3.2002806663513184, 0, -1.7634589672088623),
    neighbours: ["AD", "AB", "U"],
  },
  AD: {
    coordinates: new YUKA.Vector3(1.711462140083313, 0, -2.316910982131958),
    neighbours: ["AE", "AB", "AC"],
  },
  AE: {
    coordinates: new YUKA.Vector3(-0.06288325786590576, 0, -2.8165829181671143),
    neighbours: ["AG", "AD", "AA", "Z", "AF"],
  },
  AF: {
    coordinates: new YUKA.Vector3(-2.647921085357666, 0, -2.8165829181671143),
    neighbours: ["X", "Y", "AE"],
  },
  AG: {
    coordinates: new YUKA.Vector3(-0.18015336990356445, 0, -3.4386234283447266),
    neighbours: ["AE"],
  },
};

// The road segments for townA, allowing calculation of safety scores and bi-directional travel
export let roadSegments = {
  "A-D": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "B-M": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "B-C": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "C-B": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "C-D": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "C-L": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "D-A": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "D-C": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "D-J": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "D-K": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "D-L": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "D-E": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "E-F": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "E-D": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "E-H": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "F-E": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "F-G": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "G-F": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "G-H": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "G-T": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "H-E": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "H-G": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "H-R": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "H-S": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "I-D": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "I-H": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "I-J": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "I-R": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "J-D": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "J-I": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "J-K": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "J-Q": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "K-D": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "K-J": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "K-L": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "K-P": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "L-C": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "L-M": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "L-O": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "L-K": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "M-N": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "M-L": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "N-O": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "N-V": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "N-M": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "O-N": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "O-V": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "O-L": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "O-Y": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "O-P": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "P-Y": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "P-O": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "P-K": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "P-Q": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Q-P": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Q-J": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Q-R": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Q-Z": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "R-Q": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "R-I": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "R-H": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "R-S": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "R-AA": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "S-U": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "S-R": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "S-H": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "S-T": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "T-U": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "T-S": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "T-G": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "U-AB": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "U-AC": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "U-S": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "U-T": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "V-O": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "V-N": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "V-W": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "V-X": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "V-Y": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "W-V": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "W-X": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "X-W": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "X-V": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "X-Y": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "X-AF": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Y-AF": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Y-X": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Y-O": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Y-P": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Y-Z": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Z-Y": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Z-Q": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Z-AA": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "Z-AE": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AA-Z": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AA-AE": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AA-AB": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AA-R": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AB-AA": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AB-U": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AB-AC": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AB-AD": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AC-AD": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AC-AB": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AC-U": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AD-AE": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AD-AB": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AD-AC": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AE-AG": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AE-AD": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AE-AA": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AE-Z": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AE-AF": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AF-X": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AF-Y": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AF-AE": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
  "AG-AE": new RoadSegment({
    roadCondition: 3,
    trafficDensity: 2,
    visibility: 4,
    accidentHistory: 3,
    pedestrianDensity: 5,
    speedLimit: 3,
    proximityToSensitiveAreas: 2,
    emergencyResponseAccessibility: 4,
    vehicleMix: 3,
    roadWidth: 5,
    trafficSignalDensity: 3,
    pedestrianInfrastructure: 2,
    schoolZoneProximity: 4,
    constructionZones: 3,
    timeOfDay: 5,
    publicEventProximity: 3,
    weatherConditions: 2,
    signalTiming: 4,
    publicTransportProximity: 3,
    wildlifeCrossing: 5,
    localDrivingCulture: 3,
    alternativeRoutesAvailability: 2,
    networkConnectivity: 1,
  }),
};

// Function to update waypoints so i can shoot them over from experience when i swap between towns
export function updateWaypoints(newWaypoints) {
  waypoints = newWaypoints;
  // console.log("waypoints updated in Dora", waypoints);
}

function calculateSafetyScore(roadSegment) {
  // Implement the safety score calculation logic
  return (
    (roadSegment.roadCondition +
      roadSegment.trafficDensity +
      roadSegment.visibility +
      roadSegment.accidentHistory +
      roadSegment.pedestrianDensity +
      roadSegment.speedLimit +
      roadSegment.proximityToSensitiveAreas +
      roadSegment.emergencyResponseAccessibility +
      roadSegment.vehicleMix +
      roadSegment.roadWidth +
      roadSegment.trafficSignalDensity +
      roadSegment.pedestrianInfrastructure +
      roadSegment.schoolZoneProximity +
      roadSegment.constructionZones +
      roadSegment.timeOfDay +
      roadSegment.publicEventProximity +
      roadSegment.weatherConditions +
      roadSegment.signalTiming +
      roadSegment.publicTransportProximity +
      roadSegment.wildlifeCrossing +
      roadSegment.localDrivingCulture +
      roadSegment.alternativeRoutesAvailability +
      roadSegment.networkConnectivity) *
    safetyThreshold
  );
}

// Function to calculate the distances between our nodes - using my z for my y
function calculateDistance(point1, point2) {
  let dx = point1.x - point2.x;
  let dy = point1.z - point2.z; // Use z as y
  return Math.sqrt(dx * dx + dy * dy);
}

// Function to integrate safety scores and distances into the waypoints
export function integrateSafetyScoresAndDistances() {
  console.log("Active town: ", activeTownLetter);

  // Choose the appropriate road segments based on the active town
  let activeRoadSegments =
    activeTownLetter === "A" ? roadSegmentsA : roadSegmentsB;
  console.log(
    `Active road segments: ${activeRoadSegments} for town ${activeTownLetter}`
  );
  for (let waypoint in waypoints) {
    waypoints[waypoint].neighbours = waypoints[waypoint].neighbours.map(
      (neighbour) => {
        let neighbourId =
          typeof neighbour === "object" ? neighbour.id : neighbour;
        let segmentKey = waypoint + "-" + neighbourId;
        let roadSegment = activeRoadSegments[segmentKey];

        let safetyScore = roadSegment
          ? calculateSafetyScore(roadSegment)
          : null;

        // Calculate adjusted safety scores
        let adjustedSafetyScoreLess = roadSegment
          ? calculateSafetyScore(roadSegment) * 0
          : null;
        let adjustedSafetyScoreMore = roadSegment
          ? calculateSafetyScore(roadSegment) * 1.5
          : null;

        // Log the safety scores if needed
        // console.log(`Safety Score for segment ${segmentKey}: ${safetyScore}`);
        // console.log(
        //   `Adjusted Safety Score (0) for segment ${segmentKey}: ${adjustedSafetyScoreLess}`
        // );
        // console.log(
        //   `Adjusted Safety Score (0.5 more) for segment ${segmentKey}: ${adjustedSafetyScoreMore}`
        // );

        let waypointCoordinates = waypoints[waypoint].coordinates;
        let neighbourCoordinates = waypoints[neighbourId].coordinates;
        let distance = calculateDistance(
          waypointCoordinates,
          neighbourCoordinates
        );

        return { id: neighbourId, safetyScore, distance };
      }
    );
  }
}

// Randomising the roadSegement values
// Link to put in my resources: https://masteringjs.io/tutorials/fundamentals/foreach-object
export function randomizeRoadSegmentProperties(roadSegments) {
  Object.keys(roadSegments).forEach((segmentKey) => {
    const segment = roadSegments[segmentKey];

    // Iterate over each property of the RoadSegment and assign a random value between 1 and 5
    Object.keys(segment).forEach((property) => {
      // Ensure the property is one that should be randomized
      if (typeof segment[property] === "number") {
        console.log("randomising property", property);
        segment[property] = Math.floor(Math.random() * 5) + 1;
      }
    });
  });
}

// Randomise the weights of the waypoints
export function randomiseWeights() {
  for (let key in waypoints) {
    waypoints[key].weight = getRandomWeight();
  }
  // console.log("waypoints rand vals", waypoints);
}

export function randomiseIndividualNodeValues() {
  //if statement to check if active town is A or B
  if (activeTownLetter === "A") {
    // Loop through all roadSegmentsA and randomise their properties
    randomizeRoadSegmentProperties(roadSegmentsA);
    //update my sorted mesh islands

    console.log("rando a vals");
    console.log("road segments a", roadSegmentsA);
  }
  if (activeTownLetter === "B") {
    // Loop through all roadSegmentsB and randomise their properties
    randomizeRoadSegmentProperties(roadSegmentsB);
    console.log("rando b vals");
    console.log("road segments b", roadSegmentsB);
  }
}

export let meshIslands = {
  A1: { nodes: ["B", "C", "M", "L"], meshIslandWeight: null },
  A2: { nodes: ["C", "L", "K", "D"], meshIslandWeight: null },
  A3: { nodes: ["D", "J", "K"], meshIslandWeight: null },
  A4: { nodes: ["J", "I", "D"], meshIslandWeight: null },
  A5: { nodes: ["D", "I", "H", "E"], meshIslandWeight: null },
  A6: { nodes: ["E", "F", "G", "H"], meshIslandWeight: null },

  B1: { nodes: ["N", "L", "M", "O"], meshIslandWeight: null },
  B2: { nodes: ["O", "L", "P", "K"], meshIslandWeight: null },
  B3: { nodes: ["P", "K", "Q", "J"], meshIslandWeight: null },
  B4: { nodes: ["Q", "R", "J", "I"], meshIslandWeight: null },
  B5: { nodes: ["R", "I", "H"], meshIslandWeight: null },
  B6: { nodes: ["R", "S", "H"], meshIslandWeight: null },
  B7: { nodes: ["S", "T", "H", "G"], meshIslandWeight: null },

  C1: { nodes: ["W", "X", "V"], meshIslandWeight: null },
  C2: { nodes: ["V", "O", "N"], meshIslandWeight: null },
  C3: { nodes: ["V", "X", "O", "Y"], meshIslandWeight: null },
  C4: { nodes: ["Y", "O", "P"], meshIslandWeight: null },
  C5: { nodes: ["Y", "Z", "P", "Q"], meshIslandWeight: null },
  C6: { nodes: ["Z", "Q", "R", "AA"], meshIslandWeight: null },
  C7: { nodes: ["AA", "AB", "R", "U", "S"], meshIslandWeight: null },
  C8: { nodes: ["AB", "AC", "U"], meshIslandWeight: null },
  C9: { nodes: ["U", "S", "T"], meshIslandWeight: null },

  D1: { nodes: ["AF", "X", "Y"], meshIslandWeight: null },
  D2: { nodes: ["AF", "AE", "Y", "Z"], meshIslandWeight: null },
  D3: { nodes: ["AE", "Z", "AA"], meshIslandWeight: null },
  D4: { nodes: ["AE", "AA", "AD", "AB"], meshIslandWeight: null },
  D5: { nodes: ["AD", "AB", "AC"], meshIslandWeight: null },
};

// List of waypoint IDs
export let waypointIds = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "AA",
  "AB",
  "AC",
  "AD",
  "AE",
  "AF",
  "AG",
];

// Set the weight of specific waypoints
export function setWeight(waypointId, weight) {
  if (waypoints[waypointId]) {
    waypoints[waypointId].weight = weight;
  } else {
    // console.error(`Waypoint ${waypointId} does not exist`);
  }
}

// Generate a random number - I GOT THIS FROM STACK OVERFLOW
function getRandomNumber(min, max) {
  return Math.random() * (max - min) + min;
}
// Set my node values to the default framework given, so the dangerous areas are dangerous
export function townADefaultNodes() {
  // First loop - Set all waypoints' weights to a random number between 1 and 2
  for (let key in waypoints) {
    waypoints[key].weight = getRandomNumber(0, 1);
  }
  // console.log("Stage 2: townADefaultNodes - wp: ", waypoints);
  // Arrays for the second and third loops, now named as mesh islands
  // Now I need to set the weights of the nodes surrounding the islands too, so their safety scores fit the area
  const secondLoopMeshIslands = [
    "D1",
    "D4",
    "C3",
    "C4",
    "C7",
    "B2",
    "B5",
    "B6",
  ];
  const thirdLoopMeshIslands = ["D2", "D3", "C5", "C6", "B3", "B4", "A3", "A4"];

  // Second loop - Update waypoints associated with specified mesh islands to a random number between 2 and 3
  secondLoopMeshIslands.forEach((meshIslandKey) => {
    if (meshIslands[meshIslandKey]) {
      meshIslands[meshIslandKey].nodes.forEach((nodeKey) => {
        if (waypoints[nodeKey]) {
          waypoints[nodeKey].weight = getRandomNumber(2, 5);
        }
      });
    }
  });

  // Third loop - Update waypoints associated with specified mesh islands to a random number between 3 and 4
  thirdLoopMeshIslands.forEach((meshIslandKey) => {
    if (meshIslands[meshIslandKey]) {
      meshIslands[meshIslandKey].nodes.forEach((nodeKey) => {
        if (waypoints[nodeKey]) {
          waypoints[nodeKey].weight = getRandomNumber(5, 9);
        }
      });
    }
  });
}

// Being lazy and just copying the function
export function townBDefaultNodes() {
  // First loop - Set all waypoints' weights to a random number between 1 and 2
  for (let key in waypoints) {
    waypoints[key].weight = getRandomNumber(0, 1);
  }
  // console.log("Stage 2: townBDefaultNodes - wp: ", waypoints);
  // Arrays for the second and third loops, now named as mesh islands
  // Now I need to set the weights of the nodes surrounding the islands too, so their safety scores fit the area
  const secondLoopMeshIslands = [
    "E2",
    "E3",
    "E4",
    "E5",
    "C5",
    "C6",
    "D6",
    "D5",
    "B5",
    "A4",
    "A2",
    "B2",
  ];

  const thirdLoopMeshIslands = [
    "C2",
    "C3",
    "C4",
    "D1",
    "D3",
    "D2",
    "D4",
    "B3",
    "B4",
  ];

  // Second loop - Update waypoints associated with specified mesh islands to a random number between 2 and 3
  secondLoopMeshIslands.forEach((meshIslandKey) => {
    if (meshIslands[meshIslandKey]) {
      meshIslands[meshIslandKey].nodes.forEach((nodeKey) => {
        if (waypoints[nodeKey]) {
          waypoints[nodeKey].weight = getRandomNumber(2, 5);
        }
      });
    }
  });

  // Third loop - Update waypoints associated with specified mesh islands to a random number between 3 and 4
  thirdLoopMeshIslands.forEach((meshIslandKey) => {
    if (meshIslands[meshIslandKey]) {
      meshIslands[meshIslandKey].nodes.forEach((nodeKey) => {
        if (waypoints[nodeKey]) {
          waypoints[nodeKey].weight = getRandomNumber(5, 9);
        }
      });
    }
  });
}

//FUNCTIONALITY
export function updatePath(startId, endId, wp) {
  let currentWaypoints = wp;
  // console.log("current waypoints", currentWaypoints);
  const newPathIds = findPath(startId, endId, currentWaypoints);

  // Reset the path
  path = new YUKA.Path();

  // Add new waypoints to the path
  newPathIds.forEach((waypointId) => {
    if (waypoints[waypointId]) {
      path.add(waypoints[waypointId].coordinates);
    } else {
      // console.error(`Waypoint ${waypointId} does not exist`);
    }
  });
}
// TEMPORARY
path.add(waypoints["A"].coordinates);
path.add(waypoints["D"].coordinates);
path.add(waypoints["E"].coordinates);
path.add(waypoints["F"].coordinates);
path.add(waypoints["T"].coordinates);

// Function to generate random weights
function getRandomWeight() {
  return Math.random() * 9 + 1; // Random weight between 1 and 10
}
export let sortedMeshIslands; // Don't think this is needed I just cant remember where I am using it
export function calculateAndUpdateMeshIslandWeights(meshIslands, waypoints) {
  // console.log("Waypoints in calculateAndUpdateMeshIslandWeights", waypoints);
  // console.log(
  //   "Mesh islands in calculateAndUpdateMeshIslandWeights",
  //   meshIslands
  // );
  
  for (let island in meshIslands) {
    let totalWeight = 0;
    let nodeCount = meshIslands[island].nodes.length;

    meshIslands[island].nodes.forEach((node) => {
      if (waypoints[node] && waypoints[node].weight) {
        totalWeight += waypoints[node].weight;
        // console.log("mesh island", island, "total weight:", totalWeight);
      } else {
        // console.error(`Weight not found for node: ${node}`);
        nodeCount--; // Adjust node count if weight is missing
      }
    });

    if (nodeCount > 0) {
      let meanWeight = totalWeight / nodeCount;
      meshIslands[island].meshIslandWeight = meanWeight;
      // console.log(`Mesh island ${island} has mean weight: ${meanWeight}`);
    } else {
      // console.error(`No valid nodes with weights for island: ${island}`);
      meshIslands[island].meshIslandWeight = null;
    }
    // console.log("mesh island ", meshIslands);
  }

  // Convert to array and sort
  let sortedIslands = Object.keys(meshIslands)
    .map((key) => ({ key, ...meshIslands[key] }))
    .sort((a, b) => a.meshIslandWeight - b.meshIslandWeight);
  // console.log("random sorted islands", sortedIslands);
  return sortedIslands; // Return the sorted array directly
}
